// Search snippets are edited separately from the longer editorial headings and
// decks. These are copy choices, not Google character-limit requirements.
interface SearchMetadata { title: string; description?: string; }
export const SEARCH_METADATA: Record<string, SearchMetadata> = {
  '/': { title: 'Whole House Generator Guide | HomeGeneratorGuide' },
  '/brands/': { title: 'Generator Brands & Models | HomeGeneratorGuide' },
  '/brands/generac/': { title: 'Generac Whole House Generators | HomeGeneratorGuide' },
  '/brands/kohler/': { title: 'Kohler Whole House Generators | HomeGeneratorGuide' },
  '/brands/champion/': { title: 'Champion Standby Generators | HomeGeneratorGuide', description: 'Compare Champion 26 kW fleX and 22 kW aXis systems, fuel ratings, ATS scope, warranty and manufacturer sources before requesting installation quotes.' },
  '/brands/briggs-stratton/': { title: 'Briggs & Stratton PowerProtect | HomeGeneratorGuide', description: 'Explore Briggs & Stratton PowerProtect 040786: fuel-specific ratings, documented noise and fuel use, published price, warranty and quote-scope caveats.' },
  '/brands/cummins/': { title: 'Cummins QuietConnect Generators | HomeGeneratorGuide', description: 'Explore Cummins QuietConnect model ratings, published warranty summaries and evidence gaps. Confirm exact-model specifications before comparing quotes.' },
  '/comparisons/': { title: 'Whole House Generator Comparisons | HomeGeneratorGuide' },
  '/comparisons/five-brand-standby-generator-comparison/': { title: 'Best Whole House Generator: 5 Brands Compared (2026)' },
  '/comparisons/generac-vs-kohler/': { title: 'Generac vs Kohler: 26 kW Compared | HomeGeneratorGuide' },
  '/comparisons/generac-vs-champion/': { title: 'Generac vs Champion: 26 kW Packages | HomeGeneratorGuide' },
  '/comparisons/kohler-vs-champion/': { title: 'Kohler vs Champion: Model Comparison | HomeGeneratorGuide' },
  '/comparisons/briggs-stratton-vs-generac/': { title: 'Briggs & Stratton vs Generac | HomeGeneratorGuide' },
  '/comparisons/cummins-vs-generac/': { title: 'Cummins vs Generac: Evidence Compared | HomeGeneratorGuide', description: 'Compare selected Cummins and Generac model records, ATS scope, warranty and evidence gaps. Fuel-specific Cummins ratings remain unestablished here.' },
  '/comparisons/standby-generator-noise-levels/': { title: 'Standby Generator Noise Compared | HomeGeneratorGuide' },
  '/comparisons/standby-generator-warranty-comparison/': { title: 'Standby Generator Warranties Compared | HomeGeneratorGuide', description: 'Compare published warranty summaries for selected Generac, Kohler, Champion, Briggs and Cummins models, with coverage caveats and purchase checks.' },
  '/comparisons/standby-vs-portable/': { title: 'Standby vs Portable Generators | HomeGeneratorGuide', description: 'Compare standby and portable home backup by transfer method, fuel, installation scope and safety responsibilities. Choose around your outage needs.' },
  '/comparisons/transfer-switch-vs-interlock/': { title: 'Transfer Switch vs Panel Interlock | HomeGeneratorGuide', description: 'Understand manual and automatic transfer switches versus panel interlocks, with safety questions to ask an electrician before connecting a generator.' },
  '/cost/': { title: 'Whole House Generator Cost Guides | HomeGeneratorGuide' },
  '/cost/standby-generator-cost/': { title: 'Whole House Generator Cost: Installed Prices (2026)' },
  '/cost/installation-cost-breakdown/': { title: 'Whole House Generator Installation Cost (2026)' },
  '/cost/transfer-switch-cost/': { title: 'Generator Transfer Switch Cost | HomeGeneratorGuide' },
  '/cost/standby-generator-quote-checklist/': { title: 'Generator Quote Checklist: 16 Checks | HomeGeneratorGuide', description: 'Compare generator proposals using 16 checks for exact equipment, electrical and fuel work, permits, commissioning, warranty, exclusions and change orders.' },
  '/cost/annotated-generator-quote-example/': { title: 'Generator Quote Example Explained | HomeGeneratorGuide', description: 'Study a fictional generator proposal with annotated equipment, site work, permits, commissioning, exclusions and allowances. Use it to question real quotes.' },
  '/cost/standby-generator-ownership-cost/': { title: 'Standby Generator Ownership Cost | HomeGeneratorGuide', description: 'Plan 5- and 10-year generator ownership costs using exact-model fuel data, local fuel rates, service quotes and clearly documented assumptions.' },
  '/cost/generator-roi-outage-costs/': { title: 'Is a Standby Generator Worth It? | HomeGeneratorGuide', description: 'Assess standby-generator value using your outage history, project costs, operating expenses and household priorities, without invented payback claims.' },
  '/sizing/': { title: 'Whole House Generator Sizing Guides | HomeGeneratorGuide' },
  '/sizing/what-size-generator-do-i-need/': { title: 'Whole House Generator Sizing: What Size Do I Need?' },
  '/sizing/generator-load-management/': { title: 'Generator Load Management Explained | HomeGeneratorGuide', description: 'Understand generator load priorities, shedding, recovery and manufacturer-specific controls. Prepare questions for an installer without wiring instructions.' },
  '/sizing/whole-home-vs-essential-loads/': { title: 'Whole-Home vs Essential-Load Backup | HomeGeneratorGuide', description: 'Compare whole-panel and selected-circuit backup by transfer equipment, load priorities and installation scope. Final sizing needs a professional load plan.' },
  '/sizing/appliance-wattage-chart/': { title: 'Appliance Wattage: Running & Starting | HomeGeneratorGuide', description: 'Review manufacturer-published running and starting watt ranges for household loads. Record actual equipment data for a professional generator assessment.' },
  '/sizing/hvac-generator-sizing/': { title: 'HVAC Generator Sizing: Equipment Data | HomeGeneratorGuide', description: 'Collect AC and heat-pump nameplate data, motor-start requirements and auxiliary-heat loads before a professional generator sizing assessment.' },
  '/sizing/well-pump-generator-sizing/': { title: 'Well Pump Generator Sizing Guide | HomeGeneratorGuide', description: 'Collect well-pump and control-panel data, interpret published wattage ranges cautiously and prepare backup-power questions for qualified professionals.' },
  '/sizing/understanding-generator-ratings/': { title: 'Generator Ratings: Fuel & Output | HomeGeneratorGuide', description: 'Interpret generator nameplates, fuel-specific standby output, kW and kVA, site derating and motor-starting data without unsupported sizing shortcuts.' },
  '/sizing/what-size-for-2000-sq-ft/': { title: 'Generator Size for a 2,000 Sq. Ft. Home | HomeGeneratorGuide' },
  '/guides/first-time-buyer-guide/': { title: 'First-Time Standby Generator Buyer Guide | HomeGeneratorGuide', description: 'Plan your first standby-generator purchase around fuel, essential loads, transfer equipment, written installation quotes and ongoing local service.' },
  '/guides/natural-gas-vs-propane/': { title: 'Natural Gas vs Propane Generators | HomeGeneratorGuide', description: 'Compare natural gas and propane by site availability, model-specific output, storage, refills and running-cost assumptions before choosing standby fuel.' },
  '/guides/generator-safety-overview/': { title: 'Generator Safety: CO & Electrical Risks | HomeGeneratorGuide', description: 'Review source-linked generator safety guidance on carbon monoxide, electrical connections, gas leaks, wet equipment and emergency response.' },
  '/guides/generator-safety-carbon-monoxide/': { title: 'Generator Carbon Monoxide Safety | HomeGeneratorGuide', description: 'Read CPSC and CDC guidance on generator CO hazards, portable placement, standby installation limits, alarms, symptoms and emergency response.' },
  '/guides/generator-climate-performance/': { title: 'Generators in Cold, Heat & Altitude | HomeGeneratorGuide', description: 'Plan for cold-weather kits, heat and altitude derating, snow, airflow and fuel supply using the exact generator manual and a local site assessment.' },
  '/guides/how-long-can-generator-run/': { title: 'How Long Can a Standby Generator Run? | HomeGeneratorGuide', description: 'Understand standby-generator runtime through exact-model fuel data, supply assumptions and maintenance requirements during extended outages.' },
  '/guides/power-quality-thd-surge-protection/': { title: 'Generator THD & Surge Protection | HomeGeneratorGuide', description: 'Understand generator THD, model-rating limits, surge protection and UPS questions. Discuss sensitive-electronics requirements with qualified professionals.' },
  '/guides/generator-glossary/': { title: 'Generator Glossary: 23 Key Terms | HomeGeneratorGuide' },
  '/guides/us-power-outage-statistics/': { title: 'U.S. Power Outages: EIA 2024 Data | HomeGeneratorGuide' },
  '/installation/what-to-expect/': { title: 'Whole House Generator Installation | HomeGeneratorGuide' },
  '/installation/generator-pad-and-placement/': { title: 'Generator Placement & Pad Guide | HomeGeneratorGuide', description: 'Plan generator placement and pad requirements using exact-model clearances, opening distances and local approvals. Verify the site with qualified trades.' },
  '/installation/automatic-transfer-switch-guide/': { title: 'Automatic Transfer Switch Guide | HomeGeneratorGuide' },
  '/installation/florida-standby-generator-guide/': { title: 'Florida Generator Installation Guide | HomeGeneratorGuide', description: 'Plan a Florida standby-generator project around licensing, local permits, flood and wind siting, utility coordination and written installation scope.' },
  '/installation/state-research/': { title: 'Generator Installation: State Sources | HomeGeneratorGuide' },
  '/maintenance/generator-maintenance-checklist/': { title: 'Generator Maintenance Checklist | HomeGeneratorGuide', description: 'Use your exact generator manual to plan maintenance, record observations and service work, and know when to contact a qualified service provider.' },
  '/maintenance/model-service-schedules/': { title: 'Generator Maintenance Schedules | HomeGeneratorGuide' },
  '/models/': { title: '32 Standby Generator Configurations | HomeGeneratorGuide', description: 'Explore 32 exact standby-generator configurations with manufacturer-linked fuel ratings, sound conditions, package scope, warranty summaries and evidence gaps.' },
  '/planning/': { title: 'Generator Planning Tools & Worksheets | HomeGeneratorGuide' },
  '/planning/sizing/': { title: 'Generator Sizing Calculator & Planner | HomeGeneratorGuide' },
  '/research/': { title: 'Homeowner Generator Research Methods | HomeGeneratorGuide' },
  '/research/evidence-ledger/': { title: 'Generator Reliability Evidence & Gaps | HomeGeneratorGuide' },
};
