"""Part 2: three genuine FAQs each for the remaining article pages."""

DATA = {
'src/pages/sizing/hvac-generator-sizing.astro': [
 ("How do I find my AC tonnage?",
  "Check the condenser nameplate or original install paperwork — never the thermostat. One ton equals 12,000 BTU/hr of cooling."),
 ("Do mini-splits size differently?",
  "Yes, favorably: inverter mini-splits ramp softly with minimal surge, so a mini-split home sizes smaller than the same home on one large central compressor."),
 ("Should I replace my AC before buying a generator?",
  "If the condenser is 15+ years old and oversized, a right-sized high-SEER replacement can shrink the generator a full size. Get both quotes in the same month."),
],
'src/pages/sizing/well-pump-generator-sizing.astro': [
 ("Where do I find my pump horsepower?",
  "On the pump control box or the well record — never by guessing depth. Variable-speed constant-pressure pumps surge softer than old across-the-line pumps."),
 ("Does a bigger pressure tank let me downsize?",
  "It cuts surge frequency, not surge size — still size for one pump start. But fewer starts mean fewer coincident-surge events, which helps marginal cases."),
 ("What about my septic effluent pump?",
  "Add its surge too (roughly 3,000 W class) — full tanks back up fast, and it is easy to forget in the load list."),
],
'src/pages/sizing/whole-home-vs-essential-loads.astro': [
 ("Can I upgrade from essential to whole-home later?",
  "Partially: pad, gas, and panel work can be sized for growth, but the generator and switch are not incrementally upgradeable. Tell bidders about upgrade intent upfront."),
 ("Does load management really replace kilowatts?",
  "Often a full size of them: shedding 2–4 deferrable giants lets a 20–22 kW unit cover a 24–26 kW load list, saving thousands in equipment, gas, and pad scope."),
 ("Which adds more resale value?",
  "Managed whole-home photographs and appraises better, but a documented, permitted essential system with service records still adds credible value. Unpermitted work adds nothing."),
],
'src/pages/sizing/what-size-for-2000-sq-ft.astro': [
 ("Does a finished basement change the size?",
  "Only through its loads: basement HVAC zones, sump and ejector pumps, dehumidifiers, and entertainment circuits. Square feet never decide — the added equipment does."),
 ("What if I work from home?",
  "Add the office (computers, monitors, network gear: a few hundred watts) to the essential list and put it on UPS for the 10-second transfer gap. It rarely changes the generator size."),
 ("Should I size for a future addition or pool?",
  "Add 10–25% headroom for realistic growth, not 50–100% for fantasies. If a pool or ADU is genuinely planned, tell the bidder so infrastructure is sized once."),
],
'src/pages/sizing/appliance-wattage-chart.astro': [
 ("Why do two identical appliances show different watts?",
  "Age, efficiency, and features: a 2008 fridge and a 2024 fridge can differ by hundreds of watts. The chart gives planning ranges; nameplates give answers."),
 ("What is LRA and where do I find it?",
  "Locked-rotor amps — worst-case motor startup current, printed on compressor and pump nameplates. Multiply by voltage for startup volt-amps."),
 ("Do LED bulbs matter for sizing?",
  "Barely: twenty LEDs draw roughly 200 W with no surge. Lighting is rounding error next to any single motor start."),
],
'src/pages/sizing/understanding-generator-ratings.astro': [
 ("Can I run my standby as primary power off-grid?",
  "No — standby rating caps around 200 hours/year with no overload allowance, and off-grid duty voids the warranty. Off-grid needs prime-rated equipment (see EcoGen-style duty designs)."),
 ("Does heat derate my generator in summer?",
  "Roughly 1% per 10°F above 77°F — a 22 kW unit at 95°F delivers about 21.6 kW. Small, but stack it with altitude before dismissing it."),
 ("What is the difference between kW and kVA?",
  "kW does work; kVA includes reactive power. Motors billed in kVA need roughly 20% more headroom than their kW suggests — size the surge, not the label."),
],
'src/pages/cost/installation-cost-breakdown.astro': [
 ("What is the most commonly underestimated line item?",
  "Gas scope: trench length, rock, driveway crossings, and meter upsizes turn a $400 line into a $2,000 surprise. Demand linear feet in writing."),
 ("Should one contractor do everything?",
  "Prefer a single accountable prime with licensed electricians and gas fitters in-house or transparently subcontracted — split contracts create blame gaps at inspection time."),
 ("Can I prep anything myself to save money?",
  "Yes, safely: clear access, handle landscaping restoration yourself, and shorten runs by approving smart placement. Never DIY panel, gas, or permit work."),
],
'src/pages/cost/generator-roi-outage-costs.astro': [
 ("How do I estimate MY outage costs?",
  "Inventory your last five years: spoiled food per event, hotel nights, missed workdays, plus one tail risk (frozen pipes, flooded basement). Price each honestly — that ledger beats national averages."),
 ("Does a generator help sell faster or just higher?",
  "Both, in outage-prone markets: documented backup shortens days-on-market objections about reliability and supports the 3–5% value reports. Keep permits and service records transferable."),
 ("Should I finance or pay cash?",
  "Cash avoids interest on a depreciating install; 0% promos (12–24 mo) are free leverage if you can clear them. Never finance through a bidder who won't itemize scope first."),
],
'src/pages/cost/transfer-switch-cost.astro': [
 ("How do I know what amperage switch I need?",
  "Match the switch to your service (100/200/400 A), not the generator's kW. 400 A services need dual or 400 A switches — engineered quotes only."),
 ("Do switches wear out?",
  "Contactors last decades with exercise cycling and clean contacts; annual transfer testing during service keeps mechanisms proven. Sheltered mounting extends life."),
 ("Can my switch handle a future bigger generator?",
  "Sometimes: a 200 A service-rated ATS already covers growth to 26 kW-class units. Selected-load subpanel switches may need rework — ask before upsizing."),
],
'src/pages/brands/briggs-stratton.astro': [
 ("What does Vanguard mean on a Briggs standby?",
  "Vanguard is Briggs' commercial-grade engine line — the selling point of PowerProtect units versus residential-only blocks."),
 ("Is parts availability a risk after bankruptcy?",
  "Energy Solutions operates normally post-2020, but confirm your dealer stocks filters, batteries, and common parts — availability is a dealer question, not a logo question."),
 ("What is PowerProtect+ DX?",
  "The dealer-exclusive top trim carrying the 10-year warranty. Same capacities, longest coverage — price it against standard-trim plus risk tolerance."),
],
'src/pages/brands/champion.astro': [
 ("Why is Champion so much cheaper?",
  "Value positioning plus fewer large-home configurations — not missing kilowatts. The discount funds tanks, service plans, or panel cleanup if local service exists."),
 ("Does Champion cover large homes?",
  "Up to 26 kW aXis, which handles most managed whole-home lists. Beyond that, the liquid-cooled establishment (Generac Protector, Kohler RCL) takes over."),
 ("Is the 10-year warranty really better?",
  "On headline length, yes — unmatched standard. Read labor windows and maintenance-compliance clauses; length without local service is paper."),
],
'src/pages/brands/cummins.astro': [
 ("What does QuietConnect mean in practice?",
  "Sound-insulated, weather-protective enclosures tuned for a uniform 65 dB(A) across the 13–20 kW line — no loud outlier in the family."),
 ("Who services Cummins residential units?",
  "Cummins distributors and certified dealers — industrial-service DNA with fewer residential storefronts. Confirm one near you before committing."),
 ("Is Cummins worth it over Generac?",
  "For extreme cold or noise-sensitive lots with a local Cummins servicer: yes. For everywhere else, weigh the 2-year standard warranty honestly against the price."),
],
'src/pages/comparisons/standby-vs-portable.astro': [
 ("Can a portable power my furnace in winter?",
  "Yes via a proper inlet or interlock — furnace blowers draw modest watts. Size the blower plus fridge and lights, and never backfeed."),
 ("How much fuel does a portable burn in an outage?",
  "Far less in absolute terms, but gasoline needs refills every 8–12 hours and degrades in storage — the logistics tax standby owners never pay."),
 ("Should renters buy standby or portable?",
  "Portable (with landlord permission for inlet work) — standby is a permanent improvement to someone else's asset."),
],
'src/pages/comparisons/transfer-switch-vs-interlock.astro': [
 ("Will an interlock pass inspection everywhere?",
  "No — most AHJs allow listed panel-matched kits, but some prohibit them. Ask the inspector before buying the $69 plate."),
 ("What gauge wire does my inlet need?",
  "Sized to the breaker and run length by your electrician — inlet, breaker, and cord ends must all match amperage. Mismatched parts melt."),
 ("Can I use any kit on any panel?",
  "No — only the kit listed for your exact panel make and model. Universal plates on listed panels void the listing and fail inspection."),
],
'src/pages/installation/generator-pad-and-placement.astro': [
 ("Can the pad double as a walkway?",
  "No — keep the pad dedicated and clear. Foot traffic, planters, and stored items violate working clearances and block service access."),
 ("How do I keep the pad from settling?",
  "Compacted gravel base, proper thickness, drainage slope, and (where needed) rebar. Settlement telegraphs vibration into the unit — photograph pre-pour."),
 ("Does the pad need frost footings?",
  "Residential standby pads are typically floating slabs, not footed foundations — but expansive clay, flood zones, and seismic/wind anchoring change the answer. Ask the inspector."),
],
'src/pages/guides/first-time-buyer-guide.astro': [
 ("What should I NOT do first?",
  "Don't sign with the first door-knocker after a storm, don't buy retail boxes before sizing, and don't skip permits to save a week. All three are expensive."),
 ("How do I know a dealer is good?",
  "Factory certification, standby-specific years, parts on shelves, storm-season response commitments, and reviews about outages — not install day."),
 ("What paperwork must I keep?",
  "Load calculation, permits and inspection signoffs, warranty registration, service invoices, and the maintenance log. This folder is your resale and warranty weapon."),
],
'src/pages/guides/generator-glossary.astro': [
 ("What is an ATS in one sentence?",
  "The automatic device that moves your home between utility and generator power — the brain of every standby system."),
 ("What does prime rating mean for me?",
  "Nothing to buy — it rates off-grid primary duty. Your home needs standby (ESP) ratings; prime numbers on a residential quote are a red flag."),
 ("Why do electricians say kVA?",
  "Because motors draw apparent power above their working watts. kVA keeps the surge math honest — kW alone understates motor starts ~20%."),
],
'src/pages/guides/generator-safety-overview.astro': [
 ("Do I need a fire extinguisher near the generator?",
  "Keep an ABC-rated extinguisher accessible — but evacuation beats firefighting for fuel-fed fires. Call 911 first, fight nothing involving gas."),
 ("Are propane tanks safe beside the house?",
  "Yes within code setbacks (~10 ft typical) on proper pads with clear access. Underground tanks add aesthetics and cold-weather vaporization."),
 ("Should I shut off gas before a hurricane?",
  "No — utilities manage storm shutoffs; closing your own meter starves the generator you installed for the storm. Evacuation orders override everything: leave."),
],
'src/pages/guides/how-long-can-generator-run.astro': [
 ("Does idling between outages count toward service?",
  "Yes — exercise minutes accrue on the hour meter. Heavy-outage years plus weekly exercise can advance your service date; check the meter, not the calendar alone."),
 ("Can I pause a long run to check oil?",
  "Yes, and you should for dipstick checks every 8–24 hours: transfer back is automatic on most ATS setups, or schedule checks between storm bands. Never open hot caps or panels."),
 ("What happens when propane runs out mid-outage?",
  "The unit shuts down on fuel starvation; refills need a delivery truck that may not reach you for days. This is why tanks are sized to the worst week, not the average outage."),
],
'src/pages/guides/power-quality-thd-surge-protection.astro': [
 ("Does a UPS really matter with standby?",
  "Yes — the 10–20 second transfer gap reboots unprotected computers and drops CPAPs and routers. A UPS bridges exactly that gap, regardless of THD."),
 ("Where does whole-house surge protection install?",
  "At the main panel on the line side, by a licensed electrician — protecting both utility and generator feed paths. Point-of-use strips still cover individual gear."),
 ("Can THD damage my HVAC?",
  "High THD overheats variable-speed drives and control boards over time. Standby <5% is safe territory; the risk lives with cheap high-THD portables."),
],
'src/pages/guides/natural-gas-vs-propane.astro': [
 ("Will my gas bill explode after an outage week?",
  "A 22 kW week at half load burns roughly $450 in gas at $1.20/therm — noticeable, not ruinous. Propane for the same week runs roughly triple. Budget the fuel you chose."),
],
}
print('part 2 pages:', len(DATA))
