import assert from 'node:assert/strict';
import {readFileSync, existsSync, readdirSync, statSync} from 'node:fs';
import {join} from 'node:path';
const dir='public/images/user-editorial';
const originals=readdirSync(dir).filter(x=>x.endsWith('.webp'));
assert.equal(originals.length,10,'Expected ten user-supplied WebP files in Git');
const sizes=originals.map(name=>({name,bytes:statSync(join(dir,name)).size}));
assert(sizes.every(x=>x.bytes<=500_000),'One user-supplied WebP exceeds 500 KB');
assert(sizes.reduce((a,x)=>a+x.bytes,0)<2_500_000,'Editorial WebP package exceeds 2.5 MB');
const hero=sizes.find(x=>x.name==='premium-home-at-dusk.webp');
assert(hero && hero.bytes<=200_000,'Homepage hero exceeds 200 KB');
assert(existsSync('dist/images/user-editorial/premium-home-at-dusk.webp'),'Hero not emitted in staging dist');
assert(existsSync('dist/images/user-editorial/neighborhood-power-outage-at-dusk.webp'),'Outage visual not emitted in staging dist');
const source=readFileSync('tools/sync-user-editorial-images.mjs','utf8');
assert(!source.includes('fetch(') && !source.includes('cloudfront.net'),'Image verifier may not perform network access');
const html=readFileSync('dist/index.html','utf8');
assert(html.includes('/images/user-editorial/premium-home-at-dusk.webp'),'Homepage missing hero');
assert(html.includes('fetchpriority="high"'),'Homepage hero fetch priority not high');
const headers=readFileSync('dist/_headers','utf8');
assert(headers.includes('noindex, nofollow'),'Staging response headers lost noindex');
console.log('Asset QA PASS: all ten WebPs vendored; hero '+hero.bytes+' bytes; editorial set '+sizes.reduce((a,x)=>a+x.bytes,0)+' bytes; no network build dependency.');
